In [1]:
import pandas as pd

In [ ]:
# What is SPP?
# Graphic: https://oppdthewire.com/wp-content/uploads/2017/09/IND_SPP_SPP_Info-snip.jpg
# https://oppdthewire.com/spp-membership/

In [3]:
# SPP  Hourly Load
# Historical load data rolled up at an hourly level and grouped by Area (legacy BA).
# Monthly format (daily available)
# https://marketplace.spp.org/groups/operational_data
# https://marketplace.spp.org/pages/hourly-load
load202208 = pd.read_csv("HOURLY_LOAD-202208.csv")

In [4]:
load202208

,MarketHour,CSWS,EDE,GRDA,INDN,KACY,KCPL,LES,MPS,NPPD,OKGE,OPPD,SECI,SPRM,SPS,WAUE,WFEC,WR
0,08/01/2022 06:00:00,5921.979,552.789,718.267,144.774,334.646,2165.933,450.939,1167.743,3038.855,4133.017,1725.040,736.784,400.886,4451.515,3311.000,1217.344,4156.282
1,08/01/2022 07:00:00,5676.878,518.736,760.611,134.214,312.163,2039.448,421.817,1092.053,2955.992,3977.195,1628.749,700.359,377.864,4321.825,3246.612,1171.366,3925.043
2,08/01/2022 08:00:00,5487.689,499.554,791.414,126.417,311.814,1930.839,400.730,1040.493,2877.460,3876.880,1544.144,667.656,362.290,4224.715,3208.668,1143.330,3738.987
3,08/01/2022 09:00:00,5388.093,488.896,796.095,123.577,301.093,1865.714,387.193,993.037,2829.621,3826.183,1490.562,653.168,352.197,4158.655,3176.231,1123.487,3634.014
4,08/01/2022 10:00:00,5378.077,493.719,787.370,121.022,303.576,1858.928,382.089,991.326,2820.477,3811.603,1470.734,650.676,353.732,4102.959,3202.621,1114.424,3616.476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,09/01/2022 01:00:00,7772.379,844.710,984.804,191.034,363.280,2599.117,619.939,1468.947,3501.208,5709.688,2193.250,932.935,549.751,3971.176,4308.471,1436.407,5399.233
740,09/01/2022 02:00:00,7427.238,808.791,955.567,176.464,354.621,2476.311,597.850,1386.748,3423.472,5511.957,2117.423,890.655,516.126,3917.394,4190.632,1398.288,5123.417
741,09/01/2022 03:00:00,6952.782,741.009,899.568,158.262,333.600,2326.732,564.697,1285.525,3299.299,5225.879,1989.168,870.498,475.247,3700.453,4028.525,1343.675,4793.956
742,09/01/2022 04:00:00,6423.723,679.433,853.791,138.238,314.749,2118.982,506.040,1185.127,3126.090,4870.231,1817.832,813.996,431.061,3570.827,3817.862,1263.726,4370.121
743,09/01/2022 05:00:00,5929.526,613.252,705.909,120.771,289.845,1927.583,456.827,1078.378,2517.188,4583.492,1675.995,765.497,392.620,3561.145,3680.001,1181.569,4038.712

In [6]:
# SPP Area Control Error
# Over or under generation compared to scheduled
# https://marketplace.spp.org/pages/ace-chart
_10minACE = pd.read_csv("10minACE.csv")

In [7]:
_10minACE

       2022-01-14T06:00:00Z   15.9243
0      2022-01-14T06:10:00Z   23.8939
1      2022-01-14T06:20:00Z  305.7813
2      2022-01-14T06:30:00Z   38.4626
3      2022-01-14T06:40:00Z  -15.2098
4      2022-01-14T06:50:00Z  -27.9180
...                     ...       ...
38154  2022-10-06T04:10:00Z  -51.8500
38155  2022-10-06T04:20:00Z   -1.9338
38156  2022-10-06T04:30:00Z   -3.5358
38157  2022-10-06T04:40:00Z  -17.0277
38158  2022-10-06T04:50:00Z   36.5631

[38159 rows x 2 columns]

In [8]:
# https://marketplace.spp.org/pages/generation-mix-rolling-365
# Generation Mix Rolling 365 for 2022-10-06 01:00:00 (Central Time)
# Graphic view (mw) of generation mix by fuel type for the past 365 days
GenMix365 = pd.read_csv("GenMix365.csv")

In [9]:
GenMix365

,GMT MKT Interval,Coal Market,Coal Self,Diesel Fuel Oil Market,Diesel Fuel Oil Self,Hydro Market,Hydro Self,Natural Gas Market,Natural Gas Self,Nuclear Market,...,Solar Self,Waste Disposal Services Market,Waste Disposal Services Self,Wind Market,Wind Self,Waste Heat Market,Waste Heat Self,Other Market,Other Self,Load
0,2021-10-06T10:05:00Z,7941.1,3006.6,0.0,6.1,1.8,633.9,2535.5,401.4,0.0,...,0.0,0.0,8.1,0.0,7873.2,0.0,0.0,0.0,30.8,23513.258
1,2021-10-06T10:10:00Z,7986.9,3018.2,0.0,6.2,1.8,635.0,2630.9,488.5,0.0,...,0.0,0.0,8.1,0.0,7711.0,0.0,0.0,0.0,30.7,23610.196
2,2021-10-06T10:15:00Z,8093.9,3001.2,0.0,6.3,1.8,635.3,2592.7,520.3,0.0,...,0.0,0.0,8.2,0.0,7714.5,0.0,0.0,0.0,30.8,23669.651
3,2021-10-06T10:20:00Z,8162.4,3007.1,0.0,6.3,1.9,634.8,2627.5,537.7,0.0,...,0.0,0.0,8.1,0.0,7660.5,0.0,0.0,0.0,30.8,23720.972
4,2021-10-06T10:25:00Z,8251.1,3029.8,0.0,6.3,1.9,637.0,2689.0,550.8,0.0,...,0.0,0.0,8.1,0.0,7579.0,0.0,0.0,0.0,30.8,23820.915
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105115,2022-10-06T09:40:00Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105116,2022-10-06T09:45:00Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105117,2022-10-06T09:50:00Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105118,2022-10-06T09:55:00Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105119,2022-10-06T10:00:00Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

EIA data

In [ ]:
# Data API https://www.eia.gov/opendata/
# grid monitor https://www.eia.gov/electricity/gridmonitor/dashboard/electric_overview/US48/US48
# https://www.eia.gov/opendata/v1/qb.php?category=2123635